### ISSUE TITLE
CocoaPods could not find...

### ISSUE THREAD

**Issue by caomaoxin** [ArcBlock/arcblock-ios-sdk#45]
[!] CocoaPods could not find compatible versions for pod "ArcBlockSDK":
  In Podfile:
    ArcBlockSDK (from `https://github.com/ArcBlock/arcblock-ios-sdk.git`)

Specs satisfying the `ArcBlockSDK (from `https://github.com/ArcBlock/arcblock-ios-sdk.git`)` dependency were found, but they required a higher minimum deployment target.

**Comment by jonathanlu813** [comment]
Hi, the current version of ArcBlock-iOS-SDK requires the iOS deployment target to be iOS 11.0 or higher. This error might be caused by your app settings having a minimum deployment target lower than 11.0.
